name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    with:
      pypi-project-url: https://pypi.org/p/teslemetry-stream
    permissions:
      id-token: write
      contents: write
